/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: st16.c                                                *
* Font:        ËÎÌו                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Range enabled:        0000 - 007F                                  *
* Range disabled:       0000 - FFFF                                  *
* Range enabled:        65B0 - 65B0                                  *
* Range enabled:        5EFA - 5EFA                                  *
* Range enabled:        6253 - 6253                                  *
* Range enabled:        5F00 - 5F00                                  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontst16;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontst16_5EFA[ 32] = { /* code 5EFA */
  ________,_X______,
  ________,_X______,
  XXXXX_XX,XXXXX___,
  ____X___,_X__X___,
  ___X_XXX,XXXXXXX_,
  ___X____,_X__X___,
  __X___XX,XXXXX___,
  _XXXX___,_X______,
  ____X_XX,XXXXX___,
  ____X___,_X______,
  _X__X___,_X______,
  __XX_XXX,XXXXXX__,
  ___X____,_X______,
  __X_XX__,_X______,
  _X____XX,XXXXXXX_,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontst16_5F00[ 32] = { /* code 5F00 */
  ________,________,
  _XXXXXXX,XXXXXX__,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  XXXXXXXX,XXXXXXX_,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ____X___,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  __X_____,__X_____,
  _X______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontst16_6253[ 32] = { /* code 6253 */
  ___X____,________,
  ___X____,________,
  ___X__XX,XXXXXXX_,
  ___X____,__X_____,
  XXXXXX__,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X_X__,__X_____,
  ___XX___,__X_____,
  __XX____,__X_____,
  XX_X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  _X_X____,X_X_____,
  __X_____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontst16_65B0[ 32] = { /* code 65B0 */
  ___X____,________,
  ____X___,_____X__,
  _XXXXXXX,_XXXX___,
  ________,_X______,
  __X___X_,_X______,
  ___X_X__,_X______,
  XXXXXXXX,_XXXXXX_,
  ____X___,_X__X___,
  ____X___,_X__X___,
  _XXXXXXX,_X__X___,
  ____X___,_X__X___,
  __X_X_X_,_X__X___,
  _X__X__X,_X__X___,
  X___X___,X___X___,
  __X_X___,X___X___,
  ___X___X,____X___};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontst16_CharInfo[4] = {
   {  16,  16,  2, acGUI_Fontst16_5EFA } /* code 5EFA */
  ,{  16,  16,  2, acGUI_Fontst16_5F00 } /* code 5F00 */
  ,{  16,  16,  2, acGUI_Fontst16_6253 } /* code 6253 */
  ,{  16,  16,  2, acGUI_Fontst16_65B0 } /* code 65B0 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontst16_Prop4 = {
   0x65B0 /* first character */
  ,0x65B0 /* last character  */
  ,&GUI_Fontst16_CharInfo[  3] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontst16_Prop3 = {
   0x6253 /* first character */
  ,0x6253 /* last character  */
  ,&GUI_Fontst16_CharInfo[  2] /* address of first character */
  ,&GUI_Fontst16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontst16_Prop2 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_Fontst16_CharInfo[  1] /* address of first character */
  ,&GUI_Fontst16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontst16_Prop1 = {
   0x5EFA /* first character */
  ,0x5EFA /* last character  */
  ,&GUI_Fontst16_CharInfo[  0] /* address of first character */
  ,&GUI_Fontst16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontst16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontst16_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

