/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "Window_4.h"
#include "stdio.h"
#include "SongTi12.h"

/*********************************************************************
*
*       Global data
*
**********************************************************************
*/

extern uint8_t Key_Value;

WM_HWIN hWin_4;
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x00)
#define ID_HEADER_0     (GUI_ID_USER + 0x01)
#define ID_HEADER_1     (GUI_ID_USER + 0x02)
#define ID_BUTTON_0     (GUI_ID_USER + 0x03)
#define ID_BUTTON_1     (GUI_ID_USER + 0x04)
#define ID_RADIO_0     (GUI_ID_USER + 0x07)


/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
static 	char String_Show[4];

static const char *StringHZ[] = {
	"\xe8\xbf\x9e\xe6\x8e\xa5","\xe6\x96\xad\xe5\xbc\x80",//0:Á¬½Ó£¬1:¶Ï¿ª
};

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 240, 320, 0, 0x0, 0 },
  { HEADER_CreateIndirect, "HeaderTop", ID_HEADER_0, 0, 0, 240, 20, 0, 0x0, 0 },
  { HEADER_CreateIndirect, "HeaderBottom", ID_HEADER_1, 0, 300, 240, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Disconnect", ID_BUTTON_0, 0, 300, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Connect", ID_BUTTON_1, 160, 300, 80, 20, 0, 0x0, 0 },
  { RADIO_CreateIndirect, "Radio", ID_RADIO_0, 160, 50, 80, 180, 0, 0x1408, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'HeaderTop'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_HEADER_0);
    HEADER_AddItem(hItem, 80, "ApolloRobot", 14);
    //
    // Initialization of 'Radio'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
    RADIO_SetText(hItem, "RC1", 1);
    RADIO_SetText(hItem, "RC2", 2);
    RADIO_SetText(hItem, "RC3", 3);
    RADIO_SetText(hItem, "RC4", 4);
    RADIO_SetText(hItem, "RC5", 5);
    RADIO_SetText(hItem, "RC6", 6);
    RADIO_SetText(hItem, "RC7", 7);
    RADIO_SetText(hItem, "RC8", 0);
		//
		//Initialize of Button
		//
    hItem = WM_GetDialogItem(pMsg->hWin ,ID_BUTTON_0);
		BUTTON_SetFont(hItem,&GUI_FontSongTi12);
		BUTTON_SetText(hItem,StringHZ[1]);
		
		hItem = WM_GetDialogItem(pMsg->hWin ,ID_BUTTON_1);
		BUTTON_SetFont(hItem,&GUI_FontSongTi12);
		BUTTON_SetText(hItem,StringHZ[0]);

    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_HEADER_0: // Notifications sent by 'HeaderTop'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        break;
      }
      break;
    case ID_HEADER_1: // Notifications sent by 'HeaderBottom'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        break;
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Disconnect'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
						Key_Value = 0;
        break;
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Connect'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
						hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
//						Radio_Index = RADIO_GetValue(hItem);
//						sprintf(String_Show,"%d\n",Radio_Index);
						RADIO_GetText(hItem, RADIO_GetValue(hItem),String_Show,4);
						GUI_MessageBox(String_Show,"Connect Success",0);
        break;
      }
      break;
    case ID_RADIO_0: // Notifications sent by 'Radio'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        break;
      }
      break;
    }
    break;
	case WM_PAINT:
			GUI_SetColor(GUI_RED);
			GUI_SetFont(&GUI_Font16_ASCII);
			GUI_DispStringAt("Please Select RC Channel:",0,50);
	break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow_4(void);
WM_HWIN CreateWindow_4(void) {

  hWin_4 = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin_4;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
