/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "Window_Top.h"

/*********************************************************************
*
*       Public data
*
**********************************************************************
*/
extern uint8_t Key_Value;

WM_HWIN hWin_Top;
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x01)
#define ID_HEADER_0     (GUI_ID_USER + 0x04)
#define ID_BUTTON_0     (GUI_ID_USER + 0x02)
#define ID_BUTTON_1     (GUI_ID_USER + 0x03)
#define ID_BUTTON_2     (GUI_ID_USER + 0x05)
#define ID_BUTTON_3     (GUI_ID_USER + 0x06)
#define ID_BUTTON_4     (GUI_ID_USER + 0x07)
#define ID_BUTTON_5     (GUI_ID_USER + 0x08)

#define ID_TEXT_0     (GUI_ID_USER + 0x09)
#define ID_TEXT_1     (GUI_ID_USER + 0x0A)
#define ID_TEXT_2     (GUI_ID_USER + 0x0B)
#define ID_TEXT_3     (GUI_ID_USER + 0x0C)
#define ID_TEXT_4     (GUI_ID_USER + 0x0D)
#define ID_TEXT_5     (GUI_ID_USER + 0x0E)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

static const char *_acStringHZ[] = {"\xe7\xbc\x96\xe7\xa8\x8b","\xe8\x93\x9d\xe7\x89\x99",//0:编程    1:蓝牙
	"\xe6\x89\x8b\xe5\x8a\xa8\xe6\x8e\xa7\xe5\x88\xb6","\xe9\x81\xa5\xe6\x8e\xa7",          //2:手动控制  3:遥控
	"\xe8\x87\xaa\xe5\xb9\xb3\xe8\xa1\xa1","\xe7\x94\xb5\xe8\x84\x91\xe8\xbf\x9e\xe6\x8e\xa5",//4:自平衡  5:电脑连接
};

static const char *_acStringE[]={"ApolloRobot"};

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 240, 320, 0, 0x0, 0 },
	{ HEADER_CreateIndirect, "Header", ID_HEADER_0, 0, 0, 240, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_0, 20, 40, 80, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_1, 130, 40, 80, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_2, 20, 120, 80, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_3, 130, 120, 80, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_4, 20, 200, 80, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "", ID_BUTTON_5, 130, 200, 80, 50, 0, 0x0, 0 },
	{ TEXT_CreateIndirect, "2", ID_TEXT_0, 130, 90, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "1", ID_TEXT_1, 20, 90, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "4", ID_TEXT_2, 130, 170, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "3", ID_TEXT_3, 20, 170, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "5", ID_TEXT_4, 20, 250, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "6", ID_TEXT_5, 130, 250, 80, 20, 0, 0x0, 0 },

  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
					
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_LIGHTBLUE);
	  //
		//Initialize Header Top
		//
		hItem = WM_GetDialogItem(pMsg->hWin, ID_HEADER_0);
    HEADER_AddItem(hItem, 80, "ApolloRobot", 14);
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		BUTTON_SetBitmap(hItem,0,&bmprogram);
//		BUTTON_SetFont(hItem,&GUI_FontSongTi16);
//		BUTTON_SetText(hItem,_acStringHZ[0]);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetBitmap(hItem,0,&bmbt);
//		BUTTON_SetFont(hItem,&GUI_FontSongTi16);
//		BUTTON_SetText(hItem,_acStringHZ[1]);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
		BUTTON_SetBitmap(hItem,0,&bmmanual);
//		BUTTON_SetFont(hItem,&GUI_FontSongTi16);
//		BUTTON_SetText(hItem,_acStringHZ[2]);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
		BUTTON_SetBitmap(hItem,0,&bmRC);
//		BUTTON_SetFont(hItem,&GUI_FontSongTi16);
//		BUTTON_SetText(hItem,_acStringHZ[3]);
 
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
		BUTTON_SetBitmap(hItem,0,&bmSB);
//		BUTTON_SetFont(hItem,&GUI_FontSongTi16);
//		BUTTON_SetText(hItem,_acStringHZ[4]);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
		BUTTON_SetBitmap(hItem,0,&bmpc);
//		BUTTON_SetFont(hItem,&GUI_FontSongTi16);
//		BUTTON_SetText(hItem,_acStringHZ[5]);
    //
    // Initialization of TEXT
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0); // Initialization of '2'
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_FontSongTi16);
		TEXT_SetText(hItem,_acStringHZ[1]);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1); // Initialization of '1'
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_FontSongTi16);
		TEXT_SetText(hItem,_acStringHZ[0]);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);// Initialization of '4'
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_FontSongTi16);
		TEXT_SetText(hItem,_acStringHZ[3]);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3); // Initialization of '3'
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_FontSongTi16);
		TEXT_SetText(hItem,_acStringHZ[2]);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4); // Initialization of '5'
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_FontSongTi16);
		TEXT_SetText(hItem,_acStringHZ[4]);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);// Initialization of '6'
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem,&GUI_FontSongTi16);
		TEXT_SetText(hItem,_acStringHZ[5]);

    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Program'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
			break;
      case WM_NOTIFICATION_RELEASED:
						Key_Value = 1;
        break;
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Bluetooth'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
			break;
      case WM_NOTIFICATION_RELEASED:
						Key_Value = 2;
        break;
       }
      break;
    case ID_HEADER_0: // Notifications sent by 'Header'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
			break;
      case WM_NOTIFICATION_RELEASED:

        break;
      case WM_NOTIFICATION_MOVED_OUT:

        break;
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Control'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
						Key_Value = 3;
        break;
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'RC'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
						Key_Value = 4;
        break;
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Self Banlance'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
      break;
      case WM_NOTIFICATION_RELEASED:
						Key_Value = 5;
        break;
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'PC Program'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
						Key_Value = 6;
        break;
      }
      break;

    }
    break;
	case  WM_PAINT:
		hItem = pMsg->hWin;
		GUI_SetColor(GUI_RED);
		GUI_SetFont(&GUI_Font24_ASCII);
		GUI_DispStringHCenterAt(_acStringE[0], 120, 280);
		break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow_Top(void);
WM_HWIN CreateWindow_Top(void) {

	
	GUI_SetFont(&GUI_FontSongTi16);
  hWin_Top = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin_Top;
}



/*************************** End of file ****************************/
