/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "Window_3.h"

extern uint8_t Key_Value;
WM_HWIN hWin_3;
WM_HWIN hDialog_Page1;
WM_HWIN hDialog_Page2;
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x00)
#define ID_HEADER_0     (GUI_ID_USER + 0x02)
#define ID_HEADER_1     (GUI_ID_USER + 0x03)
#define ID_BUTTON_0     (GUI_ID_USER + 0x04)
#define ID_MULTIPAGE_0     (GUI_ID_USER + 0x05)
#define ID_BUTTON_1     (GUI_ID_USER + 0x06)
#define ID_BUTTON_2     (GUI_ID_USER + 0x07)
#define ID_BUTTON_3     (GUI_ID_USER + 0x08)
#define ID_BUTTON_4     (GUI_ID_USER + 0x09)

#define ID_BUTTON_5     (GUI_ID_USER + 0x0A)
#define ID_BUTTON_6     (GUI_ID_USER + 0x0B)
#define ID_BUTTON_7     (GUI_ID_USER + 0x0C)

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 240, 320, 0, 0x0, 0 },
  { HEADER_CreateIndirect, "HeaderTop", ID_HEADER_0, 0, 0, 240, 20, 0, 0x0, 0 },
  { HEADER_CreateIndirect, "HeaderBottom", ID_HEADER_1, 0, 300, 240, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Back", ID_BUTTON_0, 0, 300, 80, 20, 0, 0x0, 0 },
  { MULTIPAGE_CreateIndirect, "Multipage", ID_MULTIPAGE_0, 0, 20, 240, 280, 0, 0x0, 0 },

  // USER START (Optionally insert additional widgets)
  // USER END
};
static const GUI_WIDGET_CREATE_INFO _aDialogCreatePage1[] = {
  { WINDOW_CreateIndirect,    "Dialog 1", 0, 0,   0, 240, 280, FRAMEWIN_CF_MOVEABLE },
  { BUTTON_CreateIndirect, "servo1_60", ID_BUTTON_5, 10, 30, 60, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "servo1_90", ID_BUTTON_6, 90, 30, 60, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "servo1_120", ID_BUTTON_7, 170, 30, 60, 20, 0, 0x0, 0 },
};
static const GUI_WIDGET_CREATE_INFO _aDialogCreatePage2[] = {
  { WINDOW_CreateIndirect,    "Dialog 2", 0,  0,   0, 240, 280, FRAMEWIN_CF_MOVEABLE },
  { BUTTON_CreateIndirect, "motor1forward", ID_BUTTON_1, 20, 80, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "motor1reverse", ID_BUTTON_2, 130, 80, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "motor2forward", ID_BUTTON_3, 20, 160, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "motor2reverse", ID_BUTTON_4, 130, 160, 80, 20, 0, 0x0, 0 },
};
/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'HeaderTop'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_HEADER_0);
    HEADER_AddItem(hItem, 80, "ApolloRobot", 14);
    //
    // Initialization of 'Back'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetText(hItem, "BACK");
    //
    // Initialization of 'Multipage'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIPAGE_0);  
		MULTIPAGE_AddPage(hItem, hDialog_Page1, "Servo");
		MULTIPAGE_AddPage(hItem, hDialog_Page2, "Motor");
    //
    // Initialization of Button
    //
//    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
//    BUTTON_SetText(hItem, "1_Forward");

//    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
//    BUTTON_SetText(hItem, "1_Reverse");

//    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
//    BUTTON_SetText(hItem, "2_Forward");

//    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
//    BUTTON_SetText(hItem, "2_Reverse");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_HEADER_0: // Notifications sent by 'HeaderTop'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        break;
      }
      break;
    case ID_HEADER_1: // Notifications sent by 'HeaderBottom'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        break;
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Back'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
						Key_Value = 0;
        break;
      }
      break;
    case ID_MULTIPAGE_0: // Notifications sent by 'Multipage'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        break;
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'motor1forward'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'motor1reverse'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'motor2forward'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'motor2reverse'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      }
      break;
    }
    break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow_3(void);
WM_HWIN CreateWindow_3(void) {
	
	hDialog_Page1 = GUI_CreateDialogBox(_aDialogCreatePage1, GUI_COUNTOF(_aDialogCreatePage1), NULL, WM_UNATTACHED, 0, 0);
	hDialog_Page2 = GUI_CreateDialogBox(_aDialogCreatePage2, GUI_COUNTOF(_aDialogCreatePage2), NULL, WM_UNATTACHED, 0, 0);
	
  hWin_3 = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin_3;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
