/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "Window_1_1.h"
#include "TEXT.h"

/*********************************************************************
*
*       Public data
*
**********************************************************************
*/
//
extern char _acText[10];
//
WM_HWIN hWin1_1;

//the name of program
extern char program_name[10];

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x00)
#define ID_HEADER_0     (GUI_ID_USER + 0x01)
#define ID_EDIT_0     	(GUI_ID_USER + 0x0A)
#define ID_EDIT_1     	(GUI_ID_USER + 0x0B)
#define ID_EDIT_2    		(GUI_ID_USER + 0x0C)
#define ID_EDIT_3     	(GUI_ID_USER + 0x0D)
#define ID_EDIT_4     	(GUI_ID_USER + 0x0E)
#define ID_EDIT_5     	(GUI_ID_USER + 0x0F)
#define ID_EDIT_6     	(GUI_ID_USER + 0x10)
#define ID_EDIT_7     	(GUI_ID_USER + 0x11)
#define ID_EDIT_8     	(GUI_ID_USER + 0x12)
#define ID_EDIT_9     	(GUI_ID_USER + 0x13)
#define ID_EDIT_10     	(GUI_ID_USER + 0x14)
#define ID_EDIT_11     	(GUI_ID_USER + 0x15)
#define ID_EDIT_12     	(GUI_ID_USER + 0x16)
#define ID_EDIT_13     	(GUI_ID_USER + 0x17)
#define ID_EDIT_14     	(GUI_ID_USER + 0x18)
#define ID_EDIT_15     	(GUI_ID_USER + 0x19)
#define ID_EDIT_16     	(GUI_ID_USER + 0x1A)
#define ID_EDIT_17     	(GUI_ID_USER + 0x1B)
#define ID_EDIT_18     	(GUI_ID_USER + 0x1C)
#define ID_EDIT_19     	(GUI_ID_USER + 0x1D)
#define ID_EDIT_20     	(GUI_ID_USER + 0x1E)
#define ID_EDIT_21     	(GUI_ID_USER + 0x1F)
#define ID_EDIT_22     	(GUI_ID_USER + 0x20)
#define ID_EDIT_23     	(GUI_ID_USER + 0x21)
#define ID_EDIT_24     	(GUI_ID_USER + 0x22)
#define ID_EDIT_25     	(GUI_ID_USER + 0x23)
#define ID_EDIT_26     	(GUI_ID_USER + 0x24)
#define ID_EDIT_27     	(GUI_ID_USER + 0x25)
#define ID_EDIT_28     	(GUI_ID_USER + 0x26)
#define ID_EDIT_29     	(GUI_ID_USER + 0x27)
#define ID_EDIT_30     	(GUI_ID_USER + 0x28)
#define ID_EDIT_31     	(GUI_ID_USER + 0x29)
#define ID_EDIT_32     	(GUI_ID_USER + 0x2A)
#define ID_EDIT_33     	(GUI_ID_USER + 0x2B)
#define ID_EDIT_34     	(GUI_ID_USER + 0x2C)
#define ID_EDIT_35     	(GUI_ID_USER + 0x2D)
#define ID_EDIT_36     	(GUI_ID_USER + 0x2E)
#define ID_EDIT_37     	(GUI_ID_USER + 0x2F)
#define ID_EDIT_38     	(GUI_ID_USER + 0x30)
#define ID_EDIT_39     	(GUI_ID_USER + 0x31)
#define ID_EDIT_40     	(GUI_ID_USER + 0x32)
#define ID_EDIT_41     	(GUI_ID_USER + 0x33)
#define ID_EDIT_42     	(GUI_ID_USER + 0x34)
#define ID_EDIT_43     	(GUI_ID_USER + 0x35)
#define ID_EDIT_44     	(GUI_ID_USER + 0x36)
#define ID_EDIT_45     	(GUI_ID_USER + 0x37)
#define ID_EDIT_46     	(GUI_ID_USER + 0x38)
#define ID_EDIT_47     	(GUI_ID_USER + 0x39)
#define ID_EDIT_48     	(GUI_ID_USER + 0x3A)
#define ID_EDIT_49     	(GUI_ID_USER + 0x3B)
#define ID_EDIT_50     	(GUI_ID_USER + 0x3C)
#define ID_EDIT_51     	(GUI_ID_USER + 0x3D)
#define ID_EDIT_52     	(GUI_ID_USER + 0x3E)
#define ID_EDIT_53     	(GUI_ID_USER + 0x3F)
#define ID_EDIT_54     	(GUI_ID_USER + 0x40)
#define ID_EDIT_55     	(GUI_ID_USER + 0x41)
#define ID_EDIT_56     	(GUI_ID_USER + 0x42)
#define ID_EDIT_57     	(GUI_ID_USER + 0x43)
#define ID_EDIT_58     	(GUI_ID_USER + 0x44)
#define ID_EDIT_59     	(GUI_ID_USER + 0x45)
#define ID_EDIT_60     	(GUI_ID_USER + 0x46)
#define ID_EDIT_61     	(GUI_ID_USER + 0x47)
#define ID_EDIT_62     	(GUI_ID_USER + 0x48)
#define ID_EDIT_63     	(GUI_ID_USER + 0x49)
#define ID_EDIT_64     	(GUI_ID_USER + 0x4A)
#define ID_EDIT_65     	(GUI_ID_USER + 0x4B)
#define ID_EDIT_66     	(GUI_ID_USER + 0x4C)
#define ID_EDIT_67     	(GUI_ID_USER + 0x4D)
#define ID_EDIT_68     	(GUI_ID_USER + 0x4E)
#define ID_EDIT_69     	(GUI_ID_USER + 0x4F)
#define ID_EDIT_70     	(GUI_ID_USER + 0x50)
#define ID_EDIT_71     	(GUI_ID_USER + 0x51)
#define ID_EDIT_72     	(GUI_ID_USER + 0x52)
#define ID_EDIT_73     	(GUI_ID_USER + 0x53)
#define ID_EDIT_74     	(GUI_ID_USER + 0x54)
#define ID_EDIT_75     	(GUI_ID_USER + 0x55)
#define ID_EDIT_76     	(GUI_ID_USER + 0x56)
#define ID_EDIT_77     	(GUI_ID_USER + 0x57)
#define ID_EDIT_78     	(GUI_ID_USER + 0x58)
#define ID_EDIT_79     	(GUI_ID_USER + 0x59)
#define ID_EDIT_80     	(GUI_ID_USER + 0x5A)
#define ID_EDIT_81     	(GUI_ID_USER + 0x5B)
#define ID_EDIT_82     	(GUI_ID_USER + 0x5C)
#define ID_EDIT_83     	(GUI_ID_USER + 0x5D)
#define ID_EDIT_84     	(GUI_ID_USER + 0x5E)
#define ID_EDIT_85     	(GUI_ID_USER + 0x5F)
#define ID_EDIT_86     	(GUI_ID_USER + 0x60)
#define ID_EDIT_87     	(GUI_ID_USER + 0x61)
#define ID_EDIT_88     	(GUI_ID_USER + 0x62)
#define ID_EDIT_89     	(GUI_ID_USER + 0x63)
#define ID_EDIT_90     	(GUI_ID_USER + 0x64)
#define ID_EDIT_91     	(GUI_ID_USER + 0x65)
#define ID_EDIT_92     	(GUI_ID_USER + 0x66)
#define ID_EDIT_93     	(GUI_ID_USER + 0x67)
#define ID_EDIT_94     	(GUI_ID_USER + 0x68)
#define ID_EDIT_95     	(GUI_ID_USER + 0x69)
#define ID_EDIT_96     	(GUI_ID_USER + 0x6A)
#define ID_EDIT_97     	(GUI_ID_USER + 0x6B)
#define ID_EDIT_98     	(GUI_ID_USER + 0x6C)
#define ID_EDIT_99     	(GUI_ID_USER + 0x6D)

#define ID_TEXT_0     (GUI_ID_USER + 0xD0)
#define ID_TEXT_1     (GUI_ID_USER + 0xD1)
#define ID_TEXT_2     (GUI_ID_USER + 0xD2)
#define ID_TEXT_3     (GUI_ID_USER + 0xD3)
#define ID_TEXT_4     (GUI_ID_USER + 0xD4)
#define ID_TEXT_5     (GUI_ID_USER + 0xD5)
#define ID_TEXT_6     (GUI_ID_USER + 0xD6)
#define ID_TEXT_7     (GUI_ID_USER + 0xD7)
#define ID_TEXT_8     (GUI_ID_USER + 0xD8)
#define ID_TEXT_9     (GUI_ID_USER + 0xD9)
#define ID_TEXT_10     (GUI_ID_USER + 0xDA)
#define ID_TEXT_11     (GUI_ID_USER + 0xDB)
#define ID_TEXT_12     (GUI_ID_USER + 0xDC)
#define ID_TEXT_13     (GUI_ID_USER + 0xDD)
#define ID_TEXT_14     (GUI_ID_USER + 0xDE)
#define ID_TEXT_15     (GUI_ID_USER + 0xDF)
#define ID_TEXT_16     (GUI_ID_USER + 0xE0)
#define ID_TEXT_17     (GUI_ID_USER + 0xE1)
#define ID_TEXT_18     (GUI_ID_USER + 0xE2)
#define ID_TEXT_19     (GUI_ID_USER + 0xE3)
#define ID_TEXT_20     (GUI_ID_USER + 0xE4)
#define ID_TEXT_21     (GUI_ID_USER + 0xE5)
#define ID_TEXT_22     (GUI_ID_USER + 0xE6)
#define ID_TEXT_23     (GUI_ID_USER + 0xE7)
#define ID_TEXT_24     (GUI_ID_USER + 0xE8)
#define ID_TEXT_25     (GUI_ID_USER + 0xE9)
#define ID_TEXT_26     (GUI_ID_USER + 0xEA)
#define ID_TEXT_27     (GUI_ID_USER + 0xEB)
#define ID_TEXT_28     (GUI_ID_USER + 0xEC)
#define ID_TEXT_29     (GUI_ID_USER + 0xED)
#define ID_TEXT_30     (GUI_ID_USER + 0xEE)
#define ID_TEXT_31     (GUI_ID_USER + 0xEF)
#define ID_TEXT_32     (GUI_ID_USER + 0xF0)
#define ID_TEXT_33     (GUI_ID_USER + 0xF1)
#define ID_TEXT_34     (GUI_ID_USER + 0xF2)
#define ID_TEXT_35     (GUI_ID_USER + 0xF3)
#define ID_TEXT_36     (GUI_ID_USER + 0xF4)
#define ID_TEXT_37     (GUI_ID_USER + 0xF5)
#define ID_TEXT_38     (GUI_ID_USER + 0xF6)
#define ID_TEXT_39     (GUI_ID_USER + 0xF7)
#define ID_TEXT_40     (GUI_ID_USER + 0xF8)
#define ID_TEXT_41     (GUI_ID_USER + 0xF9)
#define ID_TEXT_42     (GUI_ID_USER + 0xFA)
#define ID_TEXT_43     (GUI_ID_USER + 0xFB)
#define ID_TEXT_44     (GUI_ID_USER + 0xFC)
#define ID_TEXT_45     (GUI_ID_USER + 0xFD)
#define ID_TEXT_46     (GUI_ID_USER + 0xFE)
#define ID_TEXT_47     (GUI_ID_USER + 0xFF)
#define ID_TEXT_48     (GUI_ID_USER + 0x100)
#define ID_TEXT_49     (GUI_ID_USER + 0x101)
#define ID_TEXT_50     (GUI_ID_USER + 0x102)
#define ID_TEXT_51     (GUI_ID_USER + 0x103)
#define ID_TEXT_52     (GUI_ID_USER + 0x104)
#define ID_TEXT_53     (GUI_ID_USER + 0x105)
#define ID_TEXT_54     (GUI_ID_USER + 0x106)
#define ID_TEXT_55     (GUI_ID_USER + 0x107)
#define ID_TEXT_56     (GUI_ID_USER + 0x108)
#define ID_TEXT_57     (GUI_ID_USER + 0x109)
#define ID_TEXT_58     (GUI_ID_USER + 0x10A)
#define ID_TEXT_59     (GUI_ID_USER + 0x10B)
#define ID_TEXT_60     (GUI_ID_USER + 0x10C)
#define ID_TEXT_61     (GUI_ID_USER + 0x10D)
#define ID_TEXT_62     (GUI_ID_USER + 0x10E)
#define ID_TEXT_63     (GUI_ID_USER + 0x10F)
#define ID_TEXT_64     (GUI_ID_USER + 0x110)
#define ID_TEXT_65     (GUI_ID_USER + 0x111)
#define ID_TEXT_66     (GUI_ID_USER + 0x112)
#define ID_TEXT_67     (GUI_ID_USER + 0x113)
#define ID_TEXT_68     (GUI_ID_USER + 0x114)
#define ID_TEXT_69     (GUI_ID_USER + 0x115)
#define ID_TEXT_70     (GUI_ID_USER + 0x116)
#define ID_TEXT_71     (GUI_ID_USER + 0x117)
#define ID_TEXT_72     (GUI_ID_USER + 0x118)
#define ID_TEXT_73     (GUI_ID_USER + 0x119)
#define ID_TEXT_74     (GUI_ID_USER + 0x11A)
#define ID_TEXT_75     (GUI_ID_USER + 0x11B)
#define ID_TEXT_76     (GUI_ID_USER + 0x11C)
#define ID_TEXT_77     (GUI_ID_USER + 0x11D)
#define ID_TEXT_78     (GUI_ID_USER + 0x11E)
#define ID_TEXT_79     (GUI_ID_USER + 0x11F)
#define ID_TEXT_80     (GUI_ID_USER + 0x120)
#define ID_TEXT_81     (GUI_ID_USER + 0x121)
#define ID_TEXT_82     (GUI_ID_USER + 0x122)
#define ID_TEXT_83     (GUI_ID_USER + 0x123)
#define ID_TEXT_84     (GUI_ID_USER + 0x124)
#define ID_TEXT_85     (GUI_ID_USER + 0x125)
#define ID_TEXT_86     (GUI_ID_USER + 0x126)
#define ID_TEXT_87     (GUI_ID_USER + 0x127)
#define ID_TEXT_88     (GUI_ID_USER + 0x128)
#define ID_TEXT_89     (GUI_ID_USER + 0x129)


// USER START (Optionally insert additional defines)
#define ID_BUTTON_0     (GUI_ID_USER + 0x03)
#define ID_BUTTON_1     (GUI_ID_USER + 0x04)
#define ID_SCROLLBAR_0  (GUI_ID_USER + 0X05)
#define ID_BUTTON_ADD   (GUI_ID_USER + 0X06)
#define ID_BUTTON_DEL   (GUI_ID_USER + 0X07)
#define MAX_EDIT_NUM      90
#define MAX_TEXT_NUM      90
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
static int Id_Edit = 3;
//const  char*Id_Num[] = {"1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20"};
static EDIT_Handle hEdit[MAX_EDIT_NUM];
//static TEXT_Handle hText[MAX_TEXT_NUM];

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 240, 1600, 0, 0x0, 0 },
  { HEADER_CreateIndirect, "HeaderTop", ID_HEADER_0, 0, 0, 240, 20, 0, 0x0, 0 },
	{ EDIT_CreateIndirect, "", ID_EDIT_0, 60, 30, 100, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "", ID_EDIT_1, 60, 60, 100, 20, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "", ID_EDIT_2, 60, 90, 100, 20, 0, 0x64, 0 },
//  { EDIT_CreateIndirect, "Edit3", ID_EDIT_3, 60, 120, 100, 20, 0, 0x64, 0 },
//  { EDIT_CreateIndirect, "Edit4", ID_EDIT_4, 60, 150, 100, 20, 0, 0x64, 0 },
//  { EDIT_CreateIndirect, "Edit5", ID_EDIT_5, 60, 180, 100, 20, 0, 0x64, 0 },
//  { EDIT_CreateIndirect, "Edit6", ID_EDIT_6, 60, 210, 100, 20, 0, 0x64, 0 },
//  { EDIT_CreateIndirect, "Edit7", ID_EDIT_7, 60, 240, 100, 20, 0, 0x64, 0 },
//  { EDIT_CreateIndirect, "Edit8", ID_EDIT_8, 60, 270, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit9", ID_EDIT_9, 60, 300, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit10", ID_EDIT_10, 60, 330, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit11", ID_EDIT_11, 60, 360, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit12", ID_EDIT_12, 60, 390, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit13", ID_EDIT_13, 60, 420, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit14", ID_EDIT_14, 60, 450, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit15", ID_EDIT_15, 60, 480, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit16", ID_EDIT_16, 60, 510, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit17", ID_EDIT_17, 60, 540, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit18", ID_EDIT_18, 60, 570, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit19", ID_EDIT_19, 60, 600, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit20", ID_EDIT_20, 60, 630, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit21", ID_EDIT_21, 60, 660, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit22", ID_EDIT_22, 60, 690, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit23", ID_EDIT_23, 60, 720, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit24", ID_EDIT_24, 60, 750, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit25", ID_EDIT_25, 60, 780, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit26", ID_EDIT_26, 60, 810, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit27", ID_EDIT_27, 60, 840, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit28", ID_EDIT_28, 60, 870, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit29", ID_EDIT_29, 60, 900, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit30", ID_EDIT_30, 60, 930, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit31", ID_EDIT_31, 60, 960, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit32", ID_EDIT_32, 60, 990, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit33", ID_EDIT_33, 60, 1020, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit34", ID_EDIT_34, 60, 1050, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit35", ID_EDIT_35, 60, 1080, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit36", ID_EDIT_36, 60, 1110, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit37", ID_EDIT_37, 60, 1140, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit38", ID_EDIT_38, 60, 1170, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit39", ID_EDIT_39, 60, 1200, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit40", ID_EDIT_40, 60, 1230, 100, 20, 0, 0x64, 0 },
//  { EDIT_CreateIndirect, "Edit41", ID_EDIT_41, 60, 1260, 100, 20, 0, 0x64, 0 },
//  { EDIT_CreateIndirect, "Edit42", ID_EDIT_42, 60, 1290, 100, 20, 0, 0x64, 0 },
//  { EDIT_CreateIndirect, "Edit43", ID_EDIT_43, 60, 1320, 100, 20, 0, 0x64, 0 },
//  { EDIT_CreateIndirect, "Edit44", ID_EDIT_44, 60, 1350, 100, 20, 0, 0x64, 0 },
//  { EDIT_CreateIndirect, "Edit45", ID_EDIT_45, 60, 1380, 100, 20, 0, 0x64, 0 },
//  { EDIT_CreateIndirect, "Edit46", ID_EDIT_46, 60, 1410, 100, 20, 0, 0x64, 0 },
//  { EDIT_CreateIndirect, "Edit47", ID_EDIT_47, 60, 1440, 100, 20, 0, 0x64, 0 },
//  { EDIT_CreateIndirect, "Edit48", ID_EDIT_48, 60, 1470, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit49", ID_EDIT_49, 60, 1500, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit50", ID_EDIT_50, 60, 1530, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit51", ID_EDIT_51, 60, 1560, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit52", ID_EDIT_52, 60, 1590, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit53", ID_EDIT_53, 60, 1620, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit54", ID_EDIT_54, 60, 1650, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit55", ID_EDIT_55, 60, 1680, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit56", ID_EDIT_56, 60, 1710, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit57", ID_EDIT_57, 60, 1740, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit58", ID_EDIT_58, 60, 1770, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit59", ID_EDIT_59, 60, 1800, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit60", ID_EDIT_60, 60, 1830, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit61", ID_EDIT_61, 60, 1860, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit62", ID_EDIT_62, 60, 1890, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit63", ID_EDIT_63, 60, 1920, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit64", ID_EDIT_64, 60, 1950, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit65", ID_EDIT_65, 60, 1980, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit66", ID_EDIT_66, 60, 2010, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit67", ID_EDIT_67, 60, 2040, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit68", ID_EDIT_68, 60, 2070, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit69", ID_EDIT_69, 60, 2100, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit70", ID_EDIT_70, 60, 2130, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit71", ID_EDIT_71, 60, 2160, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit72", ID_EDIT_72, 60, 2190, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit73", ID_EDIT_73, 60, 2220, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit74", ID_EDIT_74, 60, 2250, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit75", ID_EDIT_75, 60, 2280, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit76", ID_EDIT_76, 60, 2310, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit77", ID_EDIT_77, 60, 2340, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit78", ID_EDIT_78, 60, 2370, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit79", ID_EDIT_79, 60, 2400, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit80", ID_EDIT_80, 60, 2430, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit81", ID_EDIT_81, 60, 2460, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit82", ID_EDIT_82, 60, 2490, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit83", ID_EDIT_83, 60, 2520, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit84", ID_EDIT_84, 60, 2550, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit85", ID_EDIT_85, 60, 2580, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit86", ID_EDIT_86, 60, 2610, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit87", ID_EDIT_87, 60, 2640, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit88", ID_EDIT_88, 60, 2670, 100, 20, 0, 0x64, 0 },
//	{ EDIT_CreateIndirect, "Edit89", ID_EDIT_89, 60, 2700, 100, 20, 0, 0x64, 0 },
//  { TEXT_CreateIndirect, "1", ID_TEXT_0, 0, 30, 40, 20, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "2", ID_TEXT_1, 0, 60, 40, 20, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "3", ID_TEXT_2, 0, 90, 40, 20, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "4", ID_TEXT_3, 0, 120, 40, 20, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "5", ID_TEXT_4, 0, 150, 40, 20, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "6", ID_TEXT_5, 0, 180, 40, 20, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "7", ID_TEXT_6, 0, 210, 40, 20, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "8", ID_TEXT_7, 0, 240, 40, 20, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "9", ID_TEXT_8, 0, 270, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "10", ID_TEXT_9, 0, 300, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "11", ID_TEXT_10, 0, 330, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "12", ID_TEXT_11, 0, 360, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "13", ID_TEXT_12, 0, 390, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "14", ID_TEXT_13, 0, 420, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "15", ID_TEXT_14, 0, 450, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "16", ID_TEXT_15, 0, 480, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "17", ID_TEXT_16, 0, 510, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "18", ID_TEXT_17, 0, 540, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "19", ID_TEXT_18, 0, 570, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "20", ID_TEXT_19, 0, 600, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "21", ID_TEXT_20, 0, 630, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "22", ID_TEXT_21, 0, 660, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "23", ID_TEXT_22, 0, 690, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "24", ID_TEXT_23, 0, 720, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "25", ID_TEXT_24, 0, 750, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "26", ID_TEXT_25, 0, 780, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "27", ID_TEXT_26, 0, 810, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "28", ID_TEXT_27, 0, 840, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "29", ID_TEXT_28, 0, 870, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "30", ID_TEXT_29, 0, 900, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "31", ID_TEXT_30, 0, 930, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "32", ID_TEXT_31, 0, 960, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "33", ID_TEXT_32, 0, 990, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "34", ID_TEXT_33, 0, 1020, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "35", ID_TEXT_34, 0, 1050, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "36", ID_TEXT_35, 0, 1080, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "37", ID_TEXT_36, 0, 1110, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "38", ID_TEXT_37, 0, 1140, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "39", ID_TEXT_38, 0, 1170, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "40", ID_TEXT_39, 0, 1200, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "41", ID_TEXT_40, 0, 1230, 40, 20, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "42", ID_TEXT_41, 0, 1260, 40, 20, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "43", ID_TEXT_42, 0, 1290, 40, 20, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "44", ID_TEXT_43, 0, 1320, 40, 20, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "45", ID_TEXT_44, 0, 1350, 40, 20, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "46", ID_TEXT_45, 0, 1380, 40, 20, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "47", ID_TEXT_46, 0, 1410, 40, 20, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "48", ID_TEXT_47, 0, 1440, 40, 20, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "49", ID_TEXT_48, 0, 1470, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "50", ID_TEXT_49, 0, 1500, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "51", ID_TEXT_50, 0, 1530, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "52", ID_TEXT_51, 0, 1560, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "53", ID_TEXT_52, 0, 1590, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "54", ID_TEXT_53, 0, 1620, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "55", ID_TEXT_54, 0, 1650, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "56", ID_TEXT_55, 0, 1680, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "57", ID_TEXT_56, 0, 1710, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "58", ID_TEXT_57, 0, 1740, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "59", ID_TEXT_58, 0, 1770, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "60", ID_TEXT_59, 0, 1800, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "61", ID_TEXT_60, 0, 1830, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "62", ID_TEXT_61, 0, 1860, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "63", ID_TEXT_62, 0, 1890, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "64", ID_TEXT_63, 0, 1920, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "65", ID_TEXT_64, 0, 1950, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "66", ID_TEXT_65, 0, 1980, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "67", ID_TEXT_66, 0, 2010, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "68", ID_TEXT_67, 0, 2040, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "69", ID_TEXT_68, 0, 2070, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "70", ID_TEXT_69, 0, 2100, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "71", ID_TEXT_70, 0, 2130, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "72", ID_TEXT_71, 0, 2160, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "73", ID_TEXT_72, 0, 2190, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "74", ID_TEXT_73, 0, 2220, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "75", ID_TEXT_74, 0, 2250, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "76", ID_TEXT_75, 0, 2280, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "77", ID_TEXT_76, 0, 2310, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "78", ID_TEXT_77, 0, 2340, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "79", ID_TEXT_78, 0, 2370, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "80", ID_TEXT_79, 0, 2400, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "81", ID_TEXT_80, 0, 2430, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "82", ID_TEXT_81, 0, 2460, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "83", ID_TEXT_82, 0, 2490, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "84", ID_TEXT_83, 0, 2520, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "85", ID_TEXT_84, 0, 2550, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "86", ID_TEXT_85, 0, 2580, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "87", ID_TEXT_86, 0, 2610, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "88", ID_TEXT_87, 0, 2640, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "89", ID_TEXT_88, 0, 2670, 40, 20, 0, 0x0, 0 },
//	{ TEXT_CreateIndirect, "90", ID_TEXT_89, 0, 2700, 40, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "BACK", ID_BUTTON_0, 0, 300, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "RUN", ID_BUTTON_1, 160, 300, 80, 20, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "ADD", ID_BUTTON_ADD, 0, 30, 40, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "DEL", ID_BUTTON_DEL, 0, 280, 40, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/


/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
	WM_SCROLL_STATE ScrollState;
	WM_HWIN hDlg;
	static int _yOld=0;
	int i;
	
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
		
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_LIGHTBLUE);
		//
		//Initialize the scrollbar
		//
		SCROLLBAR_CreateEx(220,20,20,280, hItem, WM_CF_SHOW, SCROLLBAR_CF_VERTICAL, ID_SCROLLBAR_0);
    //
		// Initialize the 'Header'
		//
    hItem = WM_GetDialogItem(pMsg->hWin, ID_HEADER_0);
    HEADER_AddItem(hItem, 80, program_name, 14);
    //
    // Initialization of Edit 1、2、3...
    //
		Id_Edit = 3;
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
		hEdit[0] = hItem;
    EDIT_SetText(hItem, "Start");
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		WM_DisableWindow(hItem);
		

		for(i =1;i<Id_Edit;i++)
		{
				hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0 + i);
				hEdit[i] = hItem;
		}

    //
    // Initialization of Text 1、2、3、4、5...
    //
//		for(i =0; i< Id_Edit; i++)
//		{
//					hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0 + i);
//					TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
//					hText[i] = hItem;
//		}
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
		
    switch(Id) {
    case ID_HEADER_0: // Notifications sent by 'HeaderTop'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        break;
      }
      break;
    case ID_EDIT_0: // Notifications sent by 'Edit0'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        break;
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'Edit1'
    case ID_EDIT_2: // Notifications sent by 'Edit2'
    case ID_EDIT_3: // Notifications sent by 'Edit3'
    case ID_EDIT_4: // Notifications sent by 'Edit4'
    case ID_EDIT_5: // Notifications sent by 'Edit5'
    case ID_EDIT_6: // Notifications sent by 'Edit6'
    case ID_EDIT_7: // Notifications sent by 'Edit7'
    case ID_EDIT_8: // Notifications sent by 'Edit8'
		case ID_EDIT_9: // Notifications sent by 'Edit9'
		case ID_EDIT_10: // Notifications sent by 'Edit10'
		case ID_EDIT_11: // Notifications sent by 'Edit11'
		case ID_EDIT_12: // Notifications sent by 'Edit12'
		case ID_EDIT_13: // Notifications sent by 'Edit13'
		case ID_EDIT_14: // Notifications sent by 'Edit14'
		case ID_EDIT_15: // Notifications sent by 'Edit15'
		case ID_EDIT_16: // Notifications sent by 'Edit16'
		case ID_EDIT_17: // Notifications sent by 'Edit17'
		case ID_EDIT_18: // Notifications sent by 'Edit18'
		case ID_EDIT_19: // Notifications sent by 'Edit19'
		case ID_EDIT_20: // Notifications sent by 'Edit20'
		case ID_EDIT_21: // Notifications sent by 'Edit21'
		case ID_EDIT_22: // Notifications sent by 'Edit22'
		case ID_EDIT_23: // Notifications sent by 'Edit23'
		case ID_EDIT_24: // Notifications sent by 'Edit24'
		case ID_EDIT_25: // Notifications sent by 'Edit25'
		case ID_EDIT_26: // Notifications sent by 'Edit26'
		case ID_EDIT_27: // Notifications sent by 'Edit27'
		case ID_EDIT_28: // Notifications sent by 'Edit28'
		case ID_EDIT_29: // Notifications sent by 'Edit29'
		case ID_EDIT_30: // Notifications sent by 'Edit30'
		case ID_EDIT_31: // Notifications sent by 'Edit31'
		case ID_EDIT_32: // Notifications sent by 'Edit32'
		case ID_EDIT_33: // Notifications sent by 'Edit33'
		case ID_EDIT_34: // Notifications sent by 'Edit34'
		case ID_EDIT_35: // Notifications sent by 'Edit35'
		case ID_EDIT_36: // Notifications sent by 'Edit36'
		case ID_EDIT_37: // Notifications sent by 'Edit37'
		case ID_EDIT_38: // Notifications sent by 'Edit38'
		case ID_EDIT_39: // Notifications sent by 'Edit39'
		case ID_EDIT_40: // Notifications sent by 'Edit40'
		case ID_EDIT_41: // Notifications sent by 'Edit41'
		case ID_EDIT_42: // Notifications sent by 'Edit42'
		case ID_EDIT_43: // Notifications sent by 'Edit43'
		case ID_EDIT_44: // Notifications sent by 'Edit44'
		case ID_EDIT_45: // Notifications sent by 'Edit45'
		case ID_EDIT_46: // Notifications sent by 'Edit46'
		case ID_EDIT_47: // Notifications sent by 'Edit47'
		case ID_EDIT_48: // Notifications sent by 'Edit48'
		case ID_EDIT_49: // Notifications sent by 'Edit49'
		case ID_EDIT_50: // Notifications sent by 'Edit50'
		case ID_EDIT_51: // Notifications sent by 'Edit51'
		case ID_EDIT_52: // Notifications sent by 'Edit52'
		case ID_EDIT_53: // Notifications sent by 'Edit53'
		case ID_EDIT_54: // Notifications sent by 'Edit54'
		case ID_EDIT_55: // Notifications sent by 'Edit55'
		case ID_EDIT_56: // Notifications sent by 'Edit56'
		case ID_EDIT_57: // Notifications sent by 'Edit57'
		case ID_EDIT_58: // Notifications sent by 'Edit58'
		case ID_EDIT_59: // Notifications sent by 'Edit59'
		case ID_EDIT_60: // Notifications sent by 'Edit60'
		case ID_EDIT_61: // Notifications sent by 'Edit61'
		case ID_EDIT_62: // Notifications sent by 'Edit62'	
		case ID_EDIT_63: // Notifications sent by 'Edit63'
		case ID_EDIT_64: // Notifications sent by 'Edit64'
		case ID_EDIT_65: // Notifications sent by 'Edit65'
		case ID_EDIT_66: // Notifications sent by 'Edit66'
		case ID_EDIT_67: // Notifications sent by 'Edit67'
		case ID_EDIT_68: // Notifications sent by 'Edit68'
		case ID_EDIT_69: // Notifications sent by 'Edit69'
		case ID_EDIT_70: // Notifications sent by 'Edit70'
		case ID_EDIT_71: // Notifications sent by 'Edit71'
		case ID_EDIT_72: // Notifications sent by 'Edit72'	
		case ID_EDIT_73: // Notifications sent by 'Edit73'
		case ID_EDIT_74: // Notifications sent by 'Edit74'
		case ID_EDIT_75: // Notifications sent by 'Edit75'
		case ID_EDIT_76: // Notifications sent by 'Edit76'
		case ID_EDIT_77: // Notifications sent by 'Edit77'
		case ID_EDIT_78: // Notifications sent by 'Edit78'
		case ID_EDIT_79: // Notifications sent by 'Edit79'
		case ID_EDIT_80: // Notifications sent by 'Edit80'
		case ID_EDIT_81: // Notifications sent by 'Edit81'
		case ID_EDIT_82: // Notifications sent by 'Edit82'	
		case ID_EDIT_83: // Notifications sent by 'Edit83'
		case ID_EDIT_84: // Notifications sent by 'Edit84'
		case ID_EDIT_85: // Notifications sent by 'Edit85'
		case ID_EDIT_86: // Notifications sent by 'Edit86'
		case ID_EDIT_87: // Notifications sent by 'Edit87'
		case ID_EDIT_88: // Notifications sent by 'Edit88'
		case ID_EDIT_89: // Notifications sent by 'Edit89'
		case ID_EDIT_90: // Notifications sent by 'Edit90'
		case ID_EDIT_91: // Notifications sent by 'Edit91'
		case ID_EDIT_92: // Notifications sent by 'Edit92'	
		case ID_EDIT_93: // Notifications sent by 'Edit93'
		case ID_EDIT_94: // Notifications sent by 'Edit94'
		case ID_EDIT_95: // Notifications sent by 'Edit95'
		case ID_EDIT_96: // Notifications sent by 'Edit96'
		case ID_EDIT_97: // Notifications sent by 'Edit97'
		case ID_EDIT_98: // Notifications sent by 'Edit98'
		case ID_EDIT_99: // Notifications sent by 'Edit99'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
						hDlg = CreateWindow_Instructor();
						WM_MakeModal(hDlg);
						GUI_ExecCreatedDialog(hDlg);
						WM_MakeModal(pMsg->hWin);
						WM_SetFocus(pMsg->hWin);
						
						if(_acText[0] != 0)
						{		EDIT_SetText(pMsg->hWinSrc,_acText);
								memset(_acText,0,10);
								EDIT_SetBkColor(pMsg->hWinSrc,EDIT_CI_ENABLED,GUI_CYAN);
						}
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:

        break;
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'BACK'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
						GUI_EndDialog(hWin1_1,0);
        break;
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'RUN'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
						_MessageBox("Save And Running ?","Message");
        break;
      }
      break;
		case ID_BUTTON_ADD: //Notifications sent by "ADD"
			switch(NCode){
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
						hEdit[Id_Edit] = EDIT_CreateEx(60,(Id_Edit+1)*30,100,20,
																					pMsg->hWin,WM_CF_SHOW,0,ID_EDIT_0+Id_Edit,100);
//						hText[Id_Edit] = TEXT_CreateAsChild(0, (Id_Edit+1)*30,40,20,pMsg->hWin,WM_CF_SHOW,ID_TEXT_0+Id_Edit,Id_Num[Id_Edit],GUI_TA_HCENTER | GUI_TA_VCENTER);
						Id_Edit++;
        break;
			}
			break;
		case ID_BUTTON_DEL: //Notifications sent by "DEL"
			switch(NCode){
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
						GUI_EndDialog(hEdit[--Id_Edit],0);
//						GUI_EndDialog(hText[Id_Edit],0);
        break;
			}
			break;
		case ID_SCROLLBAR_0: // Notifications sent by 'Scrollbar'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
				//the envent that trigger by kick the scrollbar
						WM_GetScrollState(pMsg->hWinSrc, &ScrollState);
						if (_yOld != ScrollState.v) {
							int y;
							for( y = 0; y < Id_Edit; y++)
							{
								if(hEdit[y] != NULL /*&& hText[y] != NULL*/)
								{ //the step is 30 pixels
									WM_MoveWindow(hEdit[y] , 0, (_yOld - ScrollState.v)*30);
//									WM_MoveWindow(hText[y] , 0, (_yOld - ScrollState.v)*30);
								}
							}	
						}
          _yOld = ScrollState.v;
        break;//end 
      }
      break;
    }
		break;
		case  WM_PAINT:
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow_1_1(void);
WM_HWIN CreateWindow_1_1(void) {
	
  hWin1_1 = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin1_1;
}

/*********************************************************************
*
*       _MessageBox
*/
void _MessageBox(const char* pText, const char* pCaption) {
  WM_HWIN hWin;

  hWin = MESSAGEBOX_Create(pText, pCaption, 0);
  WM_MakeModal(hWin);
  GUI_ExecCreatedDialog(hWin);
}

/*************************** End of file ****************************/
