/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "Window_4.h"
#include "stdio.h"
#include "SongTi12.h"
#include "WIDGET_MessageBox.h"
/*********************************************************************
*
*       Global data
*
**********************************************************************
*/

extern uint8_t  Key_Value;
extern u8  NRF_ADDRESS[5];//NRF24L01的地址

u8 flag_nrf_link = 0;
u8 flag_change_nrf_addr = 0;
WM_HWIN           hWin_4;
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x00)
#define ID_HEADER_0     (GUI_ID_USER + 0x01)
//#define ID_HEADER_1     (GUI_ID_USER + 0x02)
#define ID_BUTTON_0     (GUI_ID_USER + 0x03)
#define ID_BUTTON_1     (GUI_ID_USER + 0x04)
#define ID_RADIO_0      (GUI_ID_USER + 0x07)
#define ID_TEXT_EXP     (GUI_ID_USER + 0x08)

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

static const char *StringHZ[] = {
	"\xe8\xbf\x9e\xe6\x8e\xa5","\xe6\x96\xad\xe5\xbc\x80",//0:连接，1:断开
	"\xe8\xaf\xb7\xe9\x80\x89\xe6\x8b\xa9\xe9\x81\xa5\xe6\x8e\xa7\xe5\x99\xa8\xe9\x80\x9a\xe9\x81\x93:",//2:请选择遥控器通道
	"\xe8\xbf\x9e\xe6\x8e\xa5\xe6\x88\x90\xe5\x8a\x9f",//3:连接成功
	"\xe9\x80\x9a\xe9\x81\x93",//4:通道
};

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 240, 320, 0, 0x0, 0 },
  { HEADER_CreateIndirect, "HeaderTop", ID_HEADER_0, 0, 0, 240, 20, 0, 0x0, 0 },
//  { HEADER_CreateIndirect, "HeaderBottom", ID_HEADER_1, 0, 300, 240, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "断开", ID_BUTTON_0, 0, 300, 80, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "连接", ID_BUTTON_1, 160, 300, 80, 20, 0, 0x0, 0 },
  { RADIO_CreateIndirect, "Radio", ID_RADIO_0, 00, 70, 80, 180, 0, 0x1408, 0 },
  { TEXT_CreateIndirect,  "请选择遥控器通道",ID_TEXT_EXP,0, 50, 100,20,0, 0X0, 0}
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  char    str[10];
	int     nrf_channel;
	u8      Mb_Val;

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
		//
		//Initialization of windows
		//
		hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_LIGHTBLUE);
    //
    // Initialization of 'HeaderTop'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_HEADER_0);
    HEADER_AddItem(hItem, 80, "ApolloRobot", 14);
    //
    // Initialization of 'Radio'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
		RADIO_SetFont(hItem, &GUI_FontSongTi12);
		sprintf(str, "%s%s",StringHZ[4],"0");
    RADIO_SetText(hItem, str, 0);
		sprintf(str, "%s%s",StringHZ[4],"1");
    RADIO_SetText(hItem, str, 1);
		sprintf(str, "%s%s",StringHZ[4],"2");
    RADIO_SetText(hItem, str, 2);
		sprintf(str, "%s%s",StringHZ[4],"3");
    RADIO_SetText(hItem, str, 3);
		sprintf(str, "%s%s",StringHZ[4],"4");
    RADIO_SetText(hItem, str, 4);
		sprintf(str, "%s%s",StringHZ[4],"5");
    RADIO_SetText(hItem, str, 5);
		sprintf(str, "%s%s",StringHZ[4],"6");
    RADIO_SetText(hItem, str, 6);
		sprintf(str, "%s%s",StringHZ[4],"7");
    RADIO_SetText(hItem, str, 7);
		//
		//Initialize of Button
		//
    hItem = WM_GetDialogItem(pMsg->hWin ,ID_BUTTON_0);
		BUTTON_SetFont(hItem,&GUI_FontSongTi12);
		BUTTON_SetText(hItem,StringHZ[1]);
		
		hItem = WM_GetDialogItem(pMsg->hWin ,ID_BUTTON_1);
		BUTTON_SetFont(hItem,&GUI_FontSongTi12);
		BUTTON_SetText(hItem,StringHZ[0]);
		//
		//Initialization of Explanation Text
		//
		hItem = WM_GetDialogItem(pMsg->hWin ,ID_TEXT_EXP);
		TEXT_SetFont(hItem, &GUI_FontSongTi12);
		TEXT_SetText(hItem, StringHZ[2]);
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
//    case ID_HEADER_0: // Notifications sent by 'HeaderTop'
//      switch(NCode) {
//      case WM_NOTIFICATION_CLICKED:
//        break;
//      case WM_NOTIFICATION_RELEASED:
//        break;
//      case WM_NOTIFICATION_MOVED_OUT:
//        break;
//      }
//      break;
    case ID_BUTTON_0: // Notifications sent by 'Disconnect'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
						Key_Value = 0;
			      flag_nrf_link = 0;
        break;
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Connect'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
						//选择NRF通道，共8个通道，其实是更改NRF的地址
						hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
						nrf_channel = RADIO_GetValue(hItem) + 4;
						
						NRF_ADDRESS[4] = nrf_channel;
						flag_change_nrf_addr = 1;
						flag_nrf_link =  1;
						RADIO_GetText(hItem, nrf_channel,str,10);
						_MessageBox(str,StringHZ[3], &Mb_Val);
        break;
      }
      break;
    case ID_RADIO_0: // Notifications sent by 'Radio'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        break;
      }
      break;
    }
    break;
	case WM_PAINT:
	break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow_4(void);
WM_HWIN CreateWindow_4(void) {

  hWin_4 = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin_4;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
