/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "Window_Top.h"

extern uint8_t Key_Value;
WM_HWIN hWin_Top;
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x01)
#define ID_BUTTON_0     (GUI_ID_USER + 0x02)
#define ID_BUTTON_1     (GUI_ID_USER + 0x03)
#define ID_HEADER_0     (GUI_ID_USER + 0x04)
//#define ID_HEADER_1     (GUI_ID_USER + 0x05)
#define ID_BUTTON_2     (GUI_ID_USER + 0x06)
#define ID_BUTTON_3     (GUI_ID_USER + 0x07)
#define ID_BUTTON_4     (GUI_ID_USER + 0x08)
#define ID_BUTTON_5     (GUI_ID_USER + 0x09)
//#define ID_BUTTON_6     (GUI_ID_USER + 0x0C)
//#define ID_BUTTON_7     (GUI_ID_USER + 0x0D)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 240, 320, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 20, 40, 80, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 130, 40, 80, 50, 0, 0x0, 0 },
  { HEADER_CreateIndirect, "Header", ID_HEADER_0, 0, 0, 240, 20, 0, 0x0, 0 },
//  { HEADER_CreateIndirect, "Header", ID_HEADER_1, 0, 300, 240, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_2, 20, 120, 80, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_3, 130, 120, 80, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_4, 20, 200, 80, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_5, 130, 200, 80, 50, 0, 0x0, 0 },
//  { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 200, 0, 40, 20, 0, 0x0, 0 },
//  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 0, 0, 58, 20, 0, 0x64, 0 },
//  { BUTTON_CreateIndirect, "Button", ID_BUTTON_6, 0, 300, 60, 20, 0, 0x0, 0 },
//  { BUTTON_CreateIndirect, "Button", ID_BUTTON_7, 180, 300, 60, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static const char *_acStringHZ[] = {"\xe7\xbc\x96\xe7\xa8\x8b","\xe8\x93\x9d\xe7\x89\x99",
"\xe6\x89\x8b\xe5\x8a\xa8\xe6\x8e\xa7\xe5\x88\xb6","\xe9\x81\xa5\xe6\x8e\xa7","\xe8\x87\xaa\xe5\xb9\xb3\xe8\xa1\xa1",
"\xe7\x94\xb5\xe8\x84\x91\xe8\xbf\x9e\xe6\x8e\xa5"};

static const char *_acStringE[]={"ApolloRobot"};
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
					
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_LIGHTBLUE);
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
//    BUTTON_SetText(hItem, "Program");
		BUTTON_SetBitmap(hItem,0,&bmProgram);
		BUTTON_SetFont(hItem,&GUI_FontSongTi16);
		BUTTON_SetText(hItem,_acStringHZ[0]);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
//    BUTTON_SetText(hItem, "Phone");
		BUTTON_SetBitmap(hItem,0,&bmbmp4_1);
		BUTTON_SetFont(hItem,&GUI_FontSongTi16);
		BUTTON_SetText(hItem,_acStringHZ[1]);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_HEADER_0);
    HEADER_AddItem(hItem, 80, "ApolloRobot", 14);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
//    BUTTON_SetText(hItem, "Control");
		BUTTON_SetBitmap(hItem,0,&bmControl);
		BUTTON_SetFont(hItem,&GUI_FontSongTi16);
		BUTTON_SetText(hItem,_acStringHZ[2]);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
//    BUTTON_SetText(hItem, "RemoteControl");
		BUTTON_SetBitmap(hItem,0,&bmRemoteControl);
		BUTTON_SetFont(hItem,&GUI_FontSongTi16);
		BUTTON_SetText(hItem,_acStringHZ[3]);
 
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
//    BUTTON_SetText(hItem, "SelfBanlance");
		BUTTON_SetBitmap(hItem,0,&bmSelBanlance);
		BUTTON_SetFont(hItem,&GUI_FontSongTi16);
		BUTTON_SetText(hItem,_acStringHZ[4]);

    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
//    BUTTON_SetText(hItem, "PCProgram");
		BUTTON_SetBitmap(hItem,0,&bmPCProgram);
		BUTTON_SetFont(hItem,&GUI_FontSongTi16);
		BUTTON_SetText(hItem,_acStringHZ[5]);

//    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
//    BUTTON_SetText(hItem, "BACK");

//    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
//    BUTTON_SetText(hItem, "ENTER");
    // USER START (Optionally insert additional code for further widget initialization)

    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Program'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
			break;
      case WM_NOTIFICATION_RELEASED:
						Key_Value = 1;
        break;
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Bluetooth'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
			break;
      case WM_NOTIFICATION_RELEASED:
						Key_Value = 2;
        break;
       }
      break;
    case ID_HEADER_0: // Notifications sent by 'Header'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
			break;
      case WM_NOTIFICATION_RELEASED:

        break;
      case WM_NOTIFICATION_MOVED_OUT:

        break;
      }
      break;
//    case ID_HEADER_1: // Notifications sent by 'Header'
//      switch(NCode) {
//      case WM_NOTIFICATION_CLICKED:
//        break;
//      case WM_NOTIFICATION_RELEASED:
//        break;
//      case WM_NOTIFICATION_MOVED_OUT:
//        break;
//      }
//      break;
    case ID_BUTTON_2: // Notifications sent by 'Control'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
						Key_Value = 3;
        break;
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'RC'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
						Key_Value = 4;
        break;
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Self Banlance'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
      break;
      case WM_NOTIFICATION_RELEASED:
						Key_Value = 5;
        break;
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'PC Program'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        break;
      case WM_NOTIFICATION_RELEASED:
						Key_Value = 6;
        break;
      }
      break;

//    case ID_BUTTON_6: // Notifications sent by 'Button'
//      switch(NCode) {
//      case WM_NOTIFICATION_CLICKED:
//			break;
//      case WM_NOTIFICATION_RELEASED:
//						Key_Value= 0;
//        break;
//			}
//      break;
//    case ID_BUTTON_7: // Notifications sent by 'Button'
//      switch(NCode) {
//      case WM_NOTIFICATION_CLICKED:
//      break;
//      case WM_NOTIFICATION_RELEASED:

//        break;
//      }
//      break;
    }
    break;
	case  WM_PAINT:
		hItem = pMsg->hWin;
		GUI_SetColor(GUI_RED);
		GUI_SetFont(&GUI_Font24_ASCII);
		GUI_DispStringHCenterAt(_acStringE[0], 120, 280);
		break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow_Top(void);
WM_HWIN CreateWindow_Top(void) {

	GUI_UC_SetEncodeUTF8();
	GUI_SetFont(&GUI_FontSongTi16);
  hWin_Top = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin_Top;
}



/*************************** End of file ****************************/
