/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

#include "Window_Running.h"
#include "SongTi12.h"
#include "_apollorobot.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     	 (GUI_ID_USER + 0x00)
#define ID_EDIT_A          (GUI_ID_USER + 0x01)
#define ID_EDIT_B          (GUI_ID_USER + 0x02)
#define ID_TEXT_A          (GUI_ID_USER + 0x03)
#define ID_TEXT_B          (GUI_ID_USER + 0x04)

/*********************************************************************
*
*       Global data
*
**********************************************************************
*/
WM_HWIN                       hRun;
extern              _Ultrasnio ult;
extern              _Variable  var;
extern              _Car       car;
extern              _Paint    paint;
extern              _Gif        gif;
extern              _Display  display;
/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

static const char *StringHZ[] = {
	"\xe5\x81\x9c\xe6\xad\xa2",//0:停止
	"\xe7\xa8\x8b\xe5\xba\x8f\xe8\x87\xaa\xe5\x8a\xa8\xe8\xbf\x90\xe8\xa1\x8c\xe4\xb8\xad......",//1:程序自动运行中
};

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 240, 320, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "A", ID_TEXT_A, 60, 20, 120, 40, 0, 0x64, 0 },

  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/



/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
//  int     NCode;
//  int     Id;
  char distance[10] = {0};
						
  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
		//
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, GUI_WHITE);
    //
    // Initialization of 'A'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_A);
	  TEXT_SetText(hItem, "");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	  TEXT_SetFont(hItem, &GUI_Font20_ASCII);
		TEXT_SetTextColor(hItem,GUI_RED);
		
		break;
  case WM_NOTIFY_PARENT:
//    Id    = WM_GetId(pMsg->hWinSrc);
//    NCode = pMsg->Data.v;
    break;
	case WM_PAINT:
		  //运行界面每次只能显示一种图案
	    GUI_SetColor(GUI_RED);
			GUI_SetFont(&GUI_FontSongTi12);
	switch(display)
	{
		case DISP_TEXT:
				hItem = pMsg->hWin;
				GUI_DispStringHCenterAt(StringHZ[1], 120, 140);
      break;
	  case DISP_DISTANCE:
					sprintf(distance,"%dcm",(int)ult.cur_distance );
					hItem = WM_GetDialogItem(pMsg->hWin ,ID_TEXT_A);
					TEXT_SetText(hItem,distance);
				break;
	  case DISP_PAINT: //画板需清全屏
					Paint_Config(&paint);
					Init_Paint(&paint);
				break;
    case DISP_DIRECTION: //清全屏
					if(car.direction == FORWARD)
					{
						 DrawForwardIcon();
					}
					if(car.direction == BACKWARD)
					{
						 DrawBackIcon();
					}
					if(car.direction == LEFT)
					{
						 DrawLeftIcon();
					}
					if(car.direction == RIGHT)
					{
						 DrawRightIcon();
					}
					if(car.direction == STOP)
					{
						 DrawStopIcon();
					}
        break;
	 case DISP_GIF://清部分屏
				DrawGIF(gif);
		    break;
	 case DISP_VARIABLE:
		    if(var.id == VAR_A)
				{
					GUI_SetColor(GUI_RED);
					GUI_SetFont(&GUI_Font32_ASCII);
					GUI_DispDecAt(var.set_val ,120, 100, 6);//变量最大显示6位数
				}
				if(var.id == VAR_B)
				{
					GUI_SetColor(GUI_RED);
					GUI_SetFont(&GUI_Font32_ASCII);
					GUI_DispDecAt(var.set_val ,120, 180, 6);//变量最大显示6位数
				}
		    break;
			}
				break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Create_RunningWindow(void);
WM_HWIN Create_RunningWindow(void) {


  hRun = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);

  return hRun;
}

// USER START (Optionally insert additional public code)
// USER END

/***************************** 阿波罗科技 www.apollorobot.com (END OF FILE) *********************************/
